# AndroidX / Kotlin
android.useAndroidX=true
kotlin.code.style=official
org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
android.nonTransitiveRClass=true

# SDK Versions
android.compileSdk=35
android.minSdk=26
android.targetSdk=35

# Build features
android.defaults.buildfeatures.buildconfig=true
android.defaults.buildfeatures.viewbinding=true